-- Forward-only admin import contract for the existing Course Explorer schema.
-- This migration intentionally leaves catalogue data untouched. It adds only
-- import tables, their indexes, and the service-role-only RPC used by the
-- Pages Function. Each RPC call is a single database transaction.

create table if not exists public.bidding (
  id bigint generated by default as identity primary key,
  course_code text not null,
  bid_clearing_price numeric not null,
  bid_capacity integer,
  bid_n_bids integer,
  academic_year text,
  term text,
  import_key text not null,
  created_at timestamptz not null default now()
);

create table if not exists public.qguide (
  id bigint generated by default as identity primary key,
  course_code text not null,
  instructor_rating numeric not null,
  course_rating numeric not null,
  workload numeric,
  year integer,
  term text,
  import_key text not null,
  created_at timestamptz not null default now()
);

create table if not exists public.requirements_tags (
  course_code_base text primary key,
  is_core boolean,
  is_stem boolean,
  updated_at timestamptz not null default now()
);

create table if not exists public.stem_designations (
  course_code_base text primary key,
  is_stem boolean not null,
  stem_group text,
  stem_school text,
  updated_at timestamptz not null default now()
);

-- Existing installations may already have bidding/Q Guide tables. Reconcile
-- them before installing triggers or the RPC, and fail loudly rather than
-- choosing an arbitrary winner when legacy data has duplicate natural keys.
alter table public.bidding add column if not exists import_key text;
alter table public.qguide add column if not exists import_key text;

update public.bidding
set import_key = course_code || '|' || coalesce(academic_year, '') || '|' || coalesce(term, '')
where import_key is null;

update public.qguide
set import_key = course_code || '|' || coalesce(year::text, '') || '|' || coalesce(term, '')
where import_key is null;

do $$
begin
  if exists (
    select 1 from public.bidding group by import_key having count(*) > 1
  ) then
    raise exception 'Cannot add bidding import_key uniqueness: legacy duplicates require review.';
  end if;
  if exists (
    select 1 from public.qguide group by import_key having count(*) > 1
  ) then
    raise exception 'Cannot add qguide import_key uniqueness: legacy duplicates require review.';
  end if;
end;
$$;

alter table public.bidding alter column import_key set not null;
alter table public.qguide alter column import_key set not null;
create unique index if not exists bidding_import_key_unique on public.bidding (import_key);
create unique index if not exists qguide_import_key_unique on public.qguide (import_key);

create or replace function public.set_bidding_import_key()
returns trigger language plpgsql set search_path = '' as $$
begin
  new.import_key := new.course_code || '|' || coalesce(new.academic_year, '') || '|' || coalesce(new.term, '');
  return new;
end;
$$;

create or replace function public.set_qguide_import_key()
returns trigger language plpgsql set search_path = '' as $$
begin
  new.import_key := new.course_code || '|' || coalesce(new.year::text, '') || '|' || coalesce(new.term, '');
  return new;
end;
$$;

drop trigger if exists set_bidding_import_key on public.bidding;
create trigger set_bidding_import_key before insert or update of course_code, academic_year, term
on public.bidding for each row execute function public.set_bidding_import_key();

drop trigger if exists set_qguide_import_key on public.qguide;
create trigger set_qguide_import_key before insert or update of course_code, year, term
on public.qguide for each row execute function public.set_qguide_import_key();

create index if not exists idx_bidding_course_code on public.bidding (course_code);
create index if not exists idx_qguide_course_code on public.qguide (course_code);

alter table public.bidding enable row level security;
alter table public.qguide enable row level security;
alter table public.requirements_tags enable row level security;
alter table public.stem_designations enable row level security;
alter table public.uploads enable row level security;

revoke all on table public.bidding, public.qguide, public.requirements_tags, public.stem_designations from anon, authenticated;
revoke all on table public.uploads from public, anon, authenticated;
drop policy if exists uploads_public_read on public.uploads;
grant select, insert, update, delete on table public.bidding, public.qguide, public.requirements_tags, public.stem_designations, public.uploads to service_role;
grant usage, select on all sequences in schema public to service_role;

create or replace function public.admin_import(p_type text, p_filename text, p_rows jsonb)
returns integer
language plpgsql
security definer
set search_path = ''
as $$
declare
  row_count integer := jsonb_array_length(p_rows);
  has_duplicates boolean;
begin
  if jsonb_typeof(p_rows) <> 'array' or row_count < 1 or row_count > 5000 then
    raise exception 'admin_import requires 1 to 5000 rows';
  end if;

  if p_type = 'bidding' then
    select count(*) <> count(distinct course_code || '|' || coalesce(academic_year, '') || '|' || coalesce(term, ''))
      into has_duplicates
      from jsonb_to_recordset(p_rows) as x(course_code text, academic_year text, term text);
    if has_duplicates then raise exception 'Duplicate bidding import keys'; end if;
    insert into public.bidding (course_code, bid_clearing_price, bid_capacity, bid_n_bids, academic_year, term)
    select course_code, bid_clearing_price, bid_capacity, bid_n_bids, academic_year, term
    from jsonb_to_recordset(p_rows) as x(course_code text, bid_clearing_price numeric, bid_capacity integer, bid_n_bids integer, academic_year text, term text)
    on conflict (import_key) do update set bid_clearing_price = excluded.bid_clearing_price, bid_capacity = excluded.bid_capacity, bid_n_bids = excluded.bid_n_bids;
  elsif p_type = 'qguide' then
    select count(*) <> count(distinct course_code || '|' || coalesce(year::text, '') || '|' || coalesce(term, ''))
      into has_duplicates
      from jsonb_to_recordset(p_rows) as x(course_code text, year integer, term text);
    if has_duplicates then raise exception 'Duplicate qguide import keys'; end if;
    insert into public.qguide (course_code, instructor_rating, course_rating, workload, year, term)
    select course_code, instructor_rating, course_rating, workload, year, term
    from jsonb_to_recordset(p_rows) as x(course_code text, instructor_rating numeric, course_rating numeric, workload numeric, year integer, term text)
    on conflict (import_key) do update set instructor_rating = excluded.instructor_rating, course_rating = excluded.course_rating, workload = excluded.workload;
  elsif p_type = 'requirements_tags' then
    select count(*) <> count(distinct course_code_base) into has_duplicates
      from jsonb_to_recordset(p_rows) as x(course_code_base text);
    if has_duplicates then raise exception 'Duplicate requirements tag keys'; end if;
    insert into public.requirements_tags (course_code_base, is_core, is_stem)
    select course_code_base, is_core, is_stem
    from jsonb_to_recordset(p_rows) as x(course_code_base text, is_core boolean, is_stem boolean)
    on conflict (course_code_base) do update set is_core = excluded.is_core, is_stem = excluded.is_stem, updated_at = now();
  elsif p_type = 'stem_designations' then
    select count(*) <> count(distinct course_code_base) into has_duplicates
      from jsonb_to_recordset(p_rows) as x(course_code_base text);
    if has_duplicates then raise exception 'Duplicate STEM designation keys'; end if;
    insert into public.stem_designations (course_code_base, is_stem, stem_group, stem_school)
    select course_code_base, is_stem, stem_group, stem_school
    from jsonb_to_recordset(p_rows) as x(course_code_base text, is_stem boolean, stem_group text, stem_school text)
    on conflict (course_code_base) do update set is_stem = excluded.is_stem, stem_group = excluded.stem_group, stem_school = excluded.stem_school, updated_at = now();
  else
    raise exception 'Unsupported admin import type';
  end if;

  insert into public.uploads (upload_type, filename, row_count, status)
  values (p_type, nullif(btrim(p_filename), ''), row_count, 'success');
  return row_count;
end;
$$;

revoke all on function public.admin_import(text, text, jsonb) from public;
revoke all on function public.admin_import(text, text, jsonb) from anon, authenticated;
grant execute on function public.admin_import(text, text, jsonb) to service_role;
